[package]
edition = "2021"
name = "armor"
version = "0.1.0"

[dependencies]
chrono = "0.4"
dev_util = "0.1"
hex = "0.4"
image = "0.24"
log = "0.4"
rand = "0.8"
sha2 = "0.10"
uuid = {version = "1.3", features = ["v4"]}
